### PR TITLE
searchbox.html

### PR DESCRIPTION
**Pull request by sam192011**

### CODE REVIEW

**Comment by Visgean** [comment]
What is the end goal of this?

**Comment by sam192011** [comment]
Not sure what I did, but tried adding a search box using some reference from the internet.

**Comment by qaisjp** [comment]
This won't work. Sorry.

**Comment by Visgean** [comment]
Yeah but there is no backend to search in nor there are any other pages to search in...

**Comment by sam192011** [comment]
ahaha sorry, I was kinda clueless myself.

**Comment by Visgean** [comment]
But if you want to experiment with this project you can do it in your forked repository, but there is no need to pull request that changes...

**Comment by sam192011** [comment]
oh, okay.

**Pull request closed without merging**
